neo4j:
    image: neo4j:3.5
    volumes:
      - ~/neo4j/data:/data
    ports:
      - "17474:7474"
      - "17687:7687"

mongodb:
    build: ../docker-mongodb
    ports:
      - "27017:27017"
    volumes: 
      - /tmp/mongodb:/data

app:
    build: .
    volumes:
      - ./:/app
    links:
      - neo4j
    working_dir: /app

